# Generated by Django 4.2.1 on 2023-06-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weatherapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="type",
            field=models.CharField(
                choices=[
                    ("sunny", "Sunny"),
                    ("cloudy", "Cloudy"),
                    ("windy", "Windy"),
                    ("rainy", "Rainy"),
                    ("stormy", "Stormy"),
                ],
                default=" ",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
